//Cities Actions
export const CITIES_LOADING = "CITIES_LOADING";
export const GET_CITIES = "GET_CITIES";
export const GET_CITY_BY_ID = "GET_CITY_BY_ID";

//Itineraries Actions
export const ITINERARIES_LOADING = "ITINERARIES_LOADING";
export const GET_ITINERARIES_BY_CITY = "GET_ITINERARIES_BY_CITY";

//Activities Actions
export const ACTIVITIES_LOADING = "ITINERARIES_LOADING";
export const GET_ACTIVITIES_BY_ITINERARY = "GET_ACTIVITIES_BY_ITINERARY";

//Users Actions
export const SET_USER_LOADING = "USER_LOADING";
export const STORE_USER_FROM_TOKEN = "STORE_USER_FROM_TOKEN";
export const CLEAR_USER_DATA = "CLEAR_USER_DATA";
export const LIKE_OR_DISLIKE = "LIKE_OR_DISLIKE";
